### ISSUE TITLE
Is it intended to be a test tool or something to be used in runtime?

### ISSUE THREAD

**Issue by jayrmotta** [jacobp100/react-image-export#13]
I want to add a feature to an app I'm working on that renders a component as a png file in runtime and then I'd share it as a base64 image to apps like whatsapp and the like, but I wonder if the dependencies like canvas, cairo, pixman and pango wouldn't make my app just too heavy.

What do you think?

Thanks in advance

**Comment by jacobp100** [comment]
It should handle your use-case: we aren't just limited to test environments!

In you need a PNG, you _need_ to have some kind of canvas. This could be the native HTML5 or node-cavas, it really just depends on where you want to run this!

I think you can use a HTML5 canvas already. If you do this, it won't pull in those dependencies.

SVG export should also be able to be run without too many dependencies, but this won't run in a browser _yet_.

Does this help?

**Comment by jayrmotta** [comment]
Yes, I'm looking into [this](https://github.com/iddan/react-native-canvas) by @jaredly`s advice.

I thought of rendering components as PNG in runtime, convert it to base64 so I can share through whatsapp, etc.

Right now I'm leaning toward rendering my component alone on the screen, capturing the screen using [this library](https://github.com/gre/react-native-view-shot), converting it to base64 and sending.

Thanks anyway, if this is something you're willing to know how I solve just let me know and I'll keep you in the loop 👊🏼

**Comment by jacobp100** [comment]
Cool! If it’s just a regular context, it should work! Let me know how it goes! 😀
